pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Source Code Available'
            }
        }

        stage('Build') {
            steps {
                dir('MavenDemo') {
                    echo 'Building Maven Project...'
                    sh 'mvn clean package'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'MavenDemo/target/*.jar', fingerprint: true
            }
        }

    }

    post {

        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }

        always {
            echo 'Pipeline Finished'
        }

    }

}
